#!/bin/bash

#
CONFIG_FILE="padavan-ng/trunk/configs/boards/XIAOMI/MI-3/kernel-3.4.x.config"

cat <<EOL >> "$CONFIG_FILE"
CONFIG_NETFILTER_XT_TARGET_NFQUEUE=m
CONFIG_NETFILTER_NETLINK_QUEUE=m
CONFIG_IP_NF_QUEUE=m
EOL

echo "OK $CONFIG_FILE"
